/*
Strimzi Kafka Bridge API Reference

Testing ProducerApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/zq2599/strimzigo"
)

func Test_openapi_ProducerApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ProducerApiService Send", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string

		resp, httpRes, err := apiClient.ProducerApi.Send(context.Background(), topicname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ProducerApiService SendToPartition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var topicname string
		var partitionid int32

		resp, httpRes, err := apiClient.ProducerApi.SendToPartition(context.Background(), topicname, partitionid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
