/*
Strimzi Kafka Bridge API Reference

The Strimzi Kafka Bridge provides a REST API for integrating HTTP based client applications with a Kafka cluster. You can use the API to create and manage consumers and send and receive records over HTTP rather than the native Kafka protocol. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the KafkaHeader type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KafkaHeader{}

// KafkaHeader struct for KafkaHeader
type KafkaHeader struct {
	Key string `json:"key"`
	// The header value in binary format, base64-encoded
	Value string `json:"value"`
}

// NewKafkaHeader instantiates a new KafkaHeader object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKafkaHeader(key string, value string) *KafkaHeader {
	this := KafkaHeader{}
	this.Key = key
	this.Value = value
	return &this
}

// NewKafkaHeaderWithDefaults instantiates a new KafkaHeader object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKafkaHeaderWithDefaults() *KafkaHeader {
	this := KafkaHeader{}
	return &this
}

// GetKey returns the Key field value
func (o *KafkaHeader) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *KafkaHeader) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *KafkaHeader) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *KafkaHeader) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *KafkaHeader) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *KafkaHeader) SetValue(v string) {
	o.Value = v
}

func (o KafkaHeader) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KafkaHeader) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

type NullableKafkaHeader struct {
	value *KafkaHeader
	isSet bool
}

func (v NullableKafkaHeader) Get() *KafkaHeader {
	return v.value
}

func (v *NullableKafkaHeader) Set(val *KafkaHeader) {
	v.value = val
	v.isSet = true
}

func (v NullableKafkaHeader) IsSet() bool {
	return v.isSet
}

func (v *NullableKafkaHeader) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKafkaHeader(val *KafkaHeader) *NullableKafkaHeader {
	return &NullableKafkaHeader{value: val, isSet: true}
}

func (v NullableKafkaHeader) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKafkaHeader) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


