/*
Strimzi Kafka Bridge API Reference

The Strimzi Kafka Bridge provides a REST API for integrating HTTP based client applications with a Kafka cluster. You can use the API to create and manage consumers and send and receive records over HTTP rather than the native Kafka protocol. 

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Partitions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Partitions{}

// Partitions struct for Partitions
type Partitions struct {
	Partitions []Partition `json:"partitions,omitempty"`
}

// NewPartitions instantiates a new Partitions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartitions() *Partitions {
	this := Partitions{}
	return &this
}

// NewPartitionsWithDefaults instantiates a new Partitions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartitionsWithDefaults() *Partitions {
	this := Partitions{}
	return &this
}

// GetPartitions returns the Partitions field value if set, zero value otherwise.
func (o *Partitions) GetPartitions() []Partition {
	if o == nil || isNil(o.Partitions) {
		var ret []Partition
		return ret
	}
	return o.Partitions
}

// GetPartitionsOk returns a tuple with the Partitions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Partitions) GetPartitionsOk() ([]Partition, bool) {
	if o == nil || isNil(o.Partitions) {
		return nil, false
	}
	return o.Partitions, true
}

// HasPartitions returns a boolean if a field has been set.
func (o *Partitions) HasPartitions() bool {
	if o != nil && !isNil(o.Partitions) {
		return true
	}

	return false
}

// SetPartitions gets a reference to the given []Partition and assigns it to the Partitions field.
func (o *Partitions) SetPartitions(v []Partition) {
	o.Partitions = v
}

func (o Partitions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Partitions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Partitions) {
		toSerialize["partitions"] = o.Partitions
	}
	return toSerialize, nil
}

type NullablePartitions struct {
	value *Partitions
	isSet bool
}

func (v NullablePartitions) Get() *Partitions {
	return v.value
}

func (v *NullablePartitions) Set(val *Partitions) {
	v.value = val
	v.isSet = true
}

func (v NullablePartitions) IsSet() bool {
	return v.isSet
}

func (v *NullablePartitions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartitions(val *Partitions) *NullablePartitions {
	return &NullablePartitions{value: val, isSet: true}
}

func (v NullablePartitions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartitions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


